### ISSUE TITLE
Project repository should be owned by DATA300L111-20S organization.

### ISSUE THREAD

**Issue by Tientuine** [DATA300L111-20S/viz.fy#4]
Please move this repository from your personal account to our DATA300L111-20S GitHub organization. You can do this as follows:

1. Go to your repository Settings on GitHub.
2. Scroll down to the "Danger Zone" and find "Transfer ownership".
3. Follow the instructions to transfer your repository to the DATA300L111-20S organization.

**Comment by NicMays334** [comment]
Transferred Ownership
